#!/usr/bin/ruby

require 'net/ping'
require 'yaml'
require 'logger'
require 'net/smtp' 

$logger     = Logger.new('healthcheck.log', 'daily')
$credentials = YAML.load_file("email.yml")
sites       = ['dev.dothinktool.com', 'app.dothinktool.com', 'www.thisonenotexists.com']

def ping(url)
	puts "healthchecking => #{url}"
	p1 = Net::Ping::TCP.new(url, 'https')
	if p1.ping?
		$logger.info("#{url} => OK")
	else
		error = "#{url} => #{p1.exception.to_s}"
		msg   = "From: healthchecker@test\nSubject: #{url} esta caido\n\n La aplicacion #{url} no paso el healthcheck y es probable que se encuentre caida.\n #{error}.\n\n"
		smtp  = Net::SMTP.new 'smtp.gmail.com', 587
	    smtp.enable_starttls
	    smtp.start('gmail.com', $credentials['email'], $credentials['password'], :login) do
	      smtp.send_message(msg, 'healthchecker@test', $credentials['send_to'])
	    end
	    $logger.error(error)
	end
end

sites.each { |site| ping(site) }